[project]
name = "htmlproofer"
version = "0.1.0"
description = ""
authors = [
    {name = "Rehan Haider", email = "email@rehanhaider.com"},
]
dependencies = ["beautifulsoup4<5.0.0,>=4.10.0", "requests<3.0.0,>=2.26.0"]
requires-python = ">=3.9"
dynamic = ["classifiers", "classifiers"]
license = {text = "AGPL-3.0"}
readme = "README.md"
keywords = ["html", "htmlproofer"]
classifiers = ["Development Status :: 5 - Production/Stable", "Intended Audience :: End Users/Desktop", "Operating System :: OS Independent", "License :: OSI Approved :: GNU Affero General Public License v3", "Programming Language :: Python", "Topic :: Internet :: WWW/HTTP", "Topic :: Software Development :: Libraries :: Python Modules"]

[project.urls]
homepage = ""
"Issue Tracker" = "https://github.com/rehanhaider/htmlproofer/issues"
repository = "https://github.com/rehanhaider/htmlproofer"


classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Programming Language :: Python",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.autopub]
project-name = "HTMLPROOFER"
git-username = "rehanhaider"
git-email = "email@rehanhaider.com"


[tool.pdm]
includes = []
[tool.pdm.dev-dependencies]
dev = []
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"


