name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - ".devcontainer/**"
      - ".vscode/**"


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: "3.8"
          architecture: "x64"
          enable-pep582: true
      - name: Install dependencies
        run: pdm install
      - name: Run tests
        run: pdm run pytest
      - name: Build the package
        run: pdm build
      - name: Deploy to PyPI
        run: pdm publish
        env:
          PDM_PUBLISH_USERNAME: __token__
          PDM_PUBLISH_PASSWORD: "${{ secrets.PYHTMLPROOFER_PYPI_API_TOKEN }}"

