name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/actions/**
      - "README.md"
      - ".gitignore"
      - ".devcontainer/**"
      - ".vscode/**"


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: "3.8"
          architecture: "x64"
          enable-pep582: true
      - name: Install dependencies
        run: pdm install
      - name: Run tests
        run: pdm run pytest
