name: Call a reusable workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - ".devcontainer/**"
      - ".vscode/**"

jobs:
  job1:
    uses: ./.github/workflows/prepare_envs

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}