name: Reusable workflow

on:
  workflow_call:
    

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    steps:
      - id: step1
        run: echo "wtf"