name: Prepare Environment

on:
  workflow_call:



jobs:
  build:
    steps:
      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: "3.8"
          architecture: "x64"
          enable-pep582: true
      - name: Install dependencies
        run: pdm install