name: Preview

on:
  pull_request:
    paths-ignore:
      - ".gitignore"
      - ".devcontainer/**"
      - ".vscode/**"

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"
          enable-pep582: true
      - name: Install dependencies
        run: pdm install
      - name: Run tests
        run: pdm run test
  deploy:
    name: Deploy
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: "3.8"
          architecture: "x64"
          enable-pep582: true
      - name: Build the package
        run: pdm build
      - name: Deploy to PyPI Test Instance
        run: pdm publish -r https://test.pypi.org/simple
        env:
          PDM_PUBLISH_USERNAME: __token__
          PDM_PUBLISH_PASSWORD: "${{ secrets.PYHTMLPROOFER_TEST_PYPI_API_TOKEN }}"
